# -*- coding: utf-8 -*-
"""COMPROG04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gcz8Qxc55uyN6anzIyIz23RedIb04Tu5
"""

p = float(input())

k = t = 1
t = (t * (365 - (k - 1))) / 365

while 1 - t < p :
  k += 1
  t = (t * (365 - (k - 1))) / 365
else :
  print(k)

d = list(map(int, input().split()))

p = d[-1]
i = 0 # change so that last line work
j = 0
n = len(d)

while j < n - 1 :
  if d[j] <= p :
    d[i], d[j] = d[j], d[i]
    i += 1 # change so that last line work
  j += 1

d[i], d[-1] = d[-1], d[i]

print(d)

q = ''
s = i = 0

while q != 'q' :
  q = input()
  if q == 'q' : break
  else :
    s += float(q)
    i += 1

if i > 0 :
  print(round(s / i, 2))
else :
  print('No Data')

a = float(input())

L = 0
U = a
x = (L + U) / 2

while abs(a - (10 ** x)) > (10 ** -10) * max(a, 10 ** x) :
  if 10 ** x > a : U = x
  elif 10 ** x < a : L = x
  x = (L + U) / 2

print(round(x, 6))

ca = input()
sa = input()
s = 0

if len(sa) != len(ca) :
  print('Incomplete answer')
else :
  for i in range(len(ca)) :
    if ca[i] == sa[i] :
      s += 1
  print(s)

il = input()
mtl = [0] * len(il)

for i in range(len(il)) :
  if il[i] == '(' : mtl[i] = '['
  elif il[i] == '[' : mtl[i] = '('
  elif il[i] == ')' : mtl[i] = ']'
  elif il[i] == ']' : mtl[i] = ')'
  else : mtl[i] = il[i]

mtl = ''.join(mtl)

if mtl == il : print(il)
else : print(mtl)

k = input()
s = input()
count = 0
symbols = ['(', ')', "'", '.', '"', ',']
mtl = []

for i in s :
  if i not in symbols : mtl.append(i)
  else : mtl.append(' ')

s = ''.join(mtl)

for i in s.split() :
  if i == k : count += 1

print(count)

h = int(input())
b = 2 * h - 1
j = 0

print(' ' * (h - 1), end = '')
print('*', end = '')
print(' ' * (h - 1), end = '')
print('')

if h > 2 :
  h -= 2
  for i in range(h, 0, -1) :
    j += 1
    print(' ' * i, end = '')
    print('*', end = '')
    print(' ' * (2 * j - 1), end = '')
    print('*', end = '')
    print(' ' * i, end = '')
    print('')

print('*' * b, end = '')

a = float(input())

L = U = 0
b = a

while b > 0 :
  b //= 10
  U += 1

x = (L + U) / 2

while abs(a - (10 ** x)) > (10 ** -10) * max(a, 10 ** x) :
  if 10 ** x > a : U = x
  elif 10 ** x < a : L = x
  x = (L + U) / 2

print(round(x, 6))

s = input()
count = 1

for i in range(1, len(s)) :
  if s[i] == s[i - 1] :
    count += 1
  else :
    print(s[i - 1], count, end = ' ')
    count = 1

print(s[len(s) - 1], count)

n = int(input())
x = []
y = []

for i in range(n) :
  s = list(map(int, input().split(' ')))
  x.append(s[0])
  y.append(s[1])

c = input()

xsl = []
ysl = []

for i in range(n) :
  if i % 2 == 0 :
    xsl.append(x[i])
    ysl.append(y[i])
  else :
    xsl.append(y[i])
    ysl.append(x[i])

if c == 'Zig-Zag' :
  print(min(xsl), max(ysl))
elif c == 'Zag-Zig' :
  print(min(ysl), max(xsl))

x, y = [], []
xsl, ysl = [], []

c = input()
while True :
  if c == 'Zig-Zag' or c == 'Zag-Zig' : break
  else :
    c = c.split()
    x += [int(c[0])]
    y += [int(c[1])]
    c = input()

for i in range(len(x)) :
  if i % 2 == 0 :
    xsl.append(x[i])
    ysl.append(y[i])
  else :
    xsl.append(y[i])
    ysl.append(x[i])

if c == 'Zig-Zag' :
  print(min(xsl), max(ysl))
elif c == 'Zag-Zig' :
  print(min(ysl), max(xsl))