# -*- coding: utf-8 -*-
"""COMPROG01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cMYdHCWKvrx9XuvoOckTWiRhyB1YOE_m
"""

print("Hello Python.\nWe're using Python 3.")

i = 2938402734091273094162387451928736401926340971234
j = 9208209384928743098273495872039847509273497
print("2938402734091273094162387451928736401926340971234 + 9208209384928743098273495872039847509273497 = ", i + j)

print("+------------------------------------------+")
print("|................................/\\........|")
print("|.............................../##\\.......|")
print("|............................../####\\......|")
print("|............................./######\\.....|")
print("|............................/########\\....|")
print("|.......__................../##########\\...|")
print("|....../##\\................/############\\..|")
print("|./\\../####\\......../\\..../##############\\.|")
print("|/##\\/######\\....../##\\../################\\|")
print("|############\\..../####\\/##################|")
print("|#############\\__/#########################|")
print("+------------------------------------------+")

import math

n = int(input())

x = (2 * math.pi) ** 0.5
y = n ** (n + 1/2)

print(x * y * (math.e) ** (-n + 1/(12 * n + 1)))
print(x * y * (math.e) ** (-n + 1/(12 * n)))

a = float(input())
b = float(input())
c = float(input())

x = ((b ** 2) - (4 * a * c)) ** 0.5

print(round(((-b - x)/(2 * a)), 3))
print(round(((-b + x)/(2 * a)), 3))

import math

w = float(input())
h = float(input())

Mosteller_Formula = ((w * h) ** 0.5)/60
Haycock_F = 0.024265 * (w ** 0.5378) * (h ** 0.3964)
Boyd_F = 0.0333 * w ** ((0.6157 - (0.0188 * math.log(w, 10)))) * (h ** 0.3)

print(Mosteller_Formula)
print(Haycock_F)
print(Boyd_F)

import math

a = math.pi - (math.factorial(10)/ (8 ** 8))
b = math.log(9.7) ** ((7/ (71 ** 0.5)) - math.sin(math.radians(40)))
c = 1.2 ** (2.3 ** (1/3))

print(round(((a + b)/ c), 6))

h1 = int(input())
m1 = int(input())
s1 = int(input())
h2 = int(input())
m2 = int(input())
s2 = int(input())

t1 = (h1 * 3600) + (m1 * 60) + s1
t2 = (h2 * 3600) + (m2 * 60) + s2

dt = t2 - t1
dh = (24 + (dt // 3600)) % 24
dt -= dh * 3600

dm = (60 + (dt // 60)) % 60
dt -= dm * 60

ds = (60 + dt) % 60

print(str(dh) + ":" + str(dm) + ":" + str(ds))