# -*- coding: utf-8 -*-
"""COMPROG03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IDWGkylhKNKl0rsQ3KTNUj1HxXwqT21x
"""

a = int(input())
b = int(input())
c = int(input())
d = int(input())
e = int(input())

if a > b : a, b = b, a
if c > d : c, d = d, c
if a > c :
  b, d = d, b
  c = a

a = e

if a > b : a, b = b, a
if c > a :
  b, d = d, b
  a = c
if a > d :
  print(d)
else :
  print(a)

d, m, y = [int(e) for e in input().split()]

n = 31
d += 15

if m in [4, 6, 9, 11] : n = 30
else :
  if m == 2 :
    if(y - 543) % 400 == 0 : n = 29
    elif(y - 543) % 4 == 0 and (y - 543) % 100 != 0 : n = 29
    else : n = 28

if d > n :
  d -= n
  m += 1
if m > 12 :
  m -= 12
  y += 1

print(str(d) + '/' + str(m) + '/' + str(y))

a, b, c, d = [int(i) for i in input().split()]

if a > b :
  a, b = b, a
  if d >= a :
    if c > d : c -= a
  else : c += a
  b = a + c + d
else :
  if c > a >= b : d += a
  if d > c : b += 2
  else : b *= 2

print(a, b, c, d)

faculty_name = ['01', '02', '20', '21', '22', '23', '24', '25', '26',
               '27', '28', '29', '30', '31', '32', '33', '34', '35',
               '36', '37', '38', '39', '40', '51', '53', '55', '58']

n = input()

if n in faculty_name : print('OK')
else : print('Error')

s = float(input())

if s >= 80 : print('A')
elif s >= 70 : print('B')
elif s >= 60 : print('C')
elif s >= 50 : print('D')
else : print('F')

a, b, c, d = [float(i) for i in input().split()]

if a > b :
  Max1 = a
  Min1 = b
else :
  Max1 = b
  Min1 = a

if c > d :
  Max2 = c
  Min2 = d
else :
  Max2 = d
  Min2 = c

if Max1 > Max2 : fMax = Max1
else : fMax = Max2

if Min1 < Min2 : fMin = Min1
else : fMin = Min2

e = (a + b + c + d - (fMax + fMin))/2

print(round(e, 2))

phone_num = ['06', '08', '09']

n = input()

if len(n) == 10 and n[0:2] in phone_num : print('Mobile number')
else : print('Not a mobile number')

n = input()

if n[0] == '-' : print('negative')
elif n[0] == '0' : print('zero')
else : print('positive')

if int(n) % 2 == 0 : print('even')
else : print('odd')

n = int(input())

if n > 2000 : print('Reject')
elif 1000 < n <= 2000 : print(str(58))
elif 500 < n <= 1000 : print(str(38))
elif 250 < n <= 500 : print(str(28))
elif 100 < n <= 250 : print(str(22))
else : print(str(18))

n = int(input())

if n // (10 ** 9) > 0 :
  n = n / (10 ** 9)
  alp = 'B'
elif n // (10 ** 6) > 0 :
  n = n / (10 ** 6)
  alp = 'M'
elif n // (10 ** 3) > 0 :
  n = n / (10 ** 3)
  alp = 'K'
else :
  alp = ''

if n > 9 : print(str(round(n)) + alp)
else : print(str(round(n, 1)) + alp)

dl = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

d = int(input())
m = int(input())
y = int(input()) - 543

if y % 400 == 0 : dl[1] += 1
elif y % 4 == 0 and y % 100 != 0 : dl[1] += 1

doy = sum(dl[:m - 1]) + d

print(doy)

from math import sin, pi

dl = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

bd, bm, by, d, m, y = [int(i) for i in input().split()]

t = 0
by -= 543
y -= 543

# red period
t += (dl[bm - 1] - bd + 1 + sum(dl[bm:]))

if bm <= 2 :
  if by % 400 == 0 : t += 1
  elif by % 4 == 0 and by % 100 != 0 : t += 1

# black period
if y - by > 0 :
  t += 365 * (y - by - 1)

# blue period
t += (sum(dl[:m - 1]) + d - 1)

if m > 1 :
  if y % 400 == 0 : t += 1
  elif y % 4 == 0 and y % 100 != 0 : t += 1

pc = round(sin((2 * pi * t)/23), 2)
ec = round(sin((2 * pi * t)/28), 2)
ic = round(sin((2 * pi * t)/33), 2)

print("{} {:.2f} {:.2f} {:.2f}".format(t, pc, ec, ic))